### ISSUE TITLE
Funpack can not process files with a "(" character in the filename or path

### ISSUE THREAD

**Issue by han-k59** [champcm/FPack#2] opened 2024-03-04 17:11 UTC
Noted that funpack can not process files with a "(" character in the filename or path. 

Maybe it is easy fix maybe not.

I have also send an email with a bug report to ccfits@heasarc.gsfc.nasa.gov 

Han

**Comment by han-k59** [comment] 2024-03-05 07:52
I got this reply from heasarc.gsfc.nasa.gov

 Hi Han,

I'm finding this bug is not just limited to Windows, but occurs on Linux as well.  Thanks for reporting this and we'll look into a fix for a future release.

-Craig

**Comment by champcm** [comment] 2024-03-05 08:06
Thanks for let me know for this issue, I will looking into it.

**Comment by champcm** [comment] 2024-03-05 09:06
I look in to code the issue is come from cfileio.c there was an algorithm that check for '(', ')', '[', ']' must have closing bracket.

**Comment by han-k59** [comment] 2024-03-05 12:24
Thanks for updating the program to CFITSIO version 4.040. I had problems to compile it myself.

Question/remarks:

1)  Is the file cfitsio.exp required? The program runs without it The reason I'm asking because I distribute fpack/funpack with my program ASTAP and there is no need to distribute unnecessary file(s).

2)  A thing you could consider is to compile to a single file with the .dll files  embedded (static libraries).

**Comment by champcm** [comment] 2024-03-08 07:01
1. I don't know but I just use a documentation of Cfitsio documentation for compile this executable.
2. This project is follow Cfitsio CMakeBuilder, there is only have this option, not have embedded library option.

**Closed as completed** 2024-03-11 04:16 UTC
